<!--
	Ivy
	
	Copyright 2020 MicroEJ Corp. All rights reserved.
	This library is provided in source code for use, modification and test, subject to license terms.
	Any modification of the source code will break MicroEJ Corp. warranties on the whole library.
-->
<ivy-module version="2.0" xmlns:ea="http://www.easyant.org" xmlns:ej="https://developer.microej.com" ej:version="2.0.0"> 
	<info organisation="com.microej.architecture.generic" module="core-testsuite" status="integration" revision="3.0.0">
		<ea:build organisation="com.is2t.easyant.buildtypes" module="build-microej-javalib" revision="4.1.+">
			<ea:property name="test.run.includes.pattern" value="**/_AllTests_*.class"/>
		</ea:build>
	</info>
	
	<configurations defaultconfmapping="default->default;provided->provided">
		<conf name="default" visibility="public" description="Runtime dependencies to other artifacts"/>
		<conf name="provided" visibility="public" description="Compile-time dependencies to APIs provided by the platform"/>
		<conf name="documentation" visibility="public" description="Documentation related to the artifact (javadoc, PDF)"/>
		<conf name="dist" visibility="public" description="Contains extra files like README.md, licenses"/>
		<conf name="source" visibility="public" description="Source code"/>
 		<conf name="test" visibility="private" description="Dependencies for test execution. It is not required for normal use of the application, and is only available for the test compilation and execution phases."/>
	</configurations>

	<publications>
		<!-- keep this empty if no specific artifact to publish -->
	</publications>
	
	<dependencies>
		<dependency org="ej.api" name="edc" rev="1.2.3"/>
		<dependency org="ej.api" name="bon" rev="1.2.3"/>
		
		<dependency conf="test->*" org="ej.library.test" name="junit" rev="1.5.0"/>
	</dependencies>
</ivy-module>
