#!/bin/bash
#
# BASH
#
# Copyright 2021-2024 MicroEJ Corp. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found with this software.

# 'run.sh' implementation for STM32 Cube Programmer.
# 'run.sh' is responsible for flashing the executable file on the target device then resetting target device

# Force to stop execution on error
set -e

if [ -z "$1" ]; then
    APPLICATION_FILE="$(pwd)/application.out"
else
    APPLICATION_FILE="$(cd $(dirname $1) ; pwd)/$(basename $1)"
fi

if [ ! -e "${APPLICATION_FILE}" ]; then
    echo "FAILED - file '${APPLICATION_FILE}' does not exist"
    exit -1
fi

# Run set_project_env.sh
. "set_project_env.sh"

if [ -z "$1" ]; then
    # Copy the binary file generated by build.sh if no parameter have been set.
    # IMPORTANT: Update the environment variable TOOLCHAIN_PROJECT_EXECUTABLE_FILE to match with yours!
    cp "$TOOLCHAIN_PROJECT_EXECUTABLE_FILE" "$APPLICATION_FILE"
fi

# Flash the board using STM32_Programmer.sh
echo ""$STLINK_CUBE_PROGRAMMER_INSTALL_DIR/bin/STM32_Programmer.sh" -c port="$STLINK_TARGET_INTERFACE" mode="$STLINK_MODE" -d "$APPLICATION_FILE" "$STLINK_START_ADDRESS" -v -rst"
"$STLINK_CUBE_PROGRAMMER_INSTALL_DIR/bin/STM32_Programmer.sh" -c port="$STLINK_TARGET_INTERFACE" mode="$STLINK_MODE" -d "$APPLICATION_FILE" "$STLINK_START_ADDRESS" -v -rst
